colLiqValorempenho = "VALOR_EMPENHO"
uiClausulaValEmpMaior = 'Maior que'
uiClausulaValEmpMenor = 'Menor que'
uiClausulaValEmpIndiferente = 'Não aplicado'
uiAmbos = "Ambos"
uiCPF = "Pessoa Física"
uiCNPJ = "Pessoa Juridíca"
uiOrdenacaoScorePior = "Pior UO+FONTE"
uiOrdenacaoScoreMedia = "Média UO+FONTE"